In [2]:
import pandas as pd

**1- Read a csv file from a URL with Pandas**

target website: https://www.football-data.co.uk/data.php

In [4]:
#reading 1 csv file from the website
url = 'https://www.football-data.co.uk/mmz4281/2526/SC0.csv'
df_premier26 = pd.read_csv(url)

In [5]:
#printing dataframe
df_premier26

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,SC0,02/08/2025,15:00,Kilmarnock,Livingston,2,2,D,2,0,...,2.05,1.80,1.94,1.96,2.05,1.93,1.87,1.83,2.06,1.91
1,SC0,02/08/2025,17:30,Motherwell,Rangers,1,1,D,0,1,...,2.03,1.83,2.03,1.88,2.03,1.85,1.97,1.77,2.08,1.91
2,SC0,03/08/2025,14:00,Falkirk,Dundee United,2,2,D,0,1,...,1.73,2.08,1.87,2.04,1.86,2.08,1.79,1.94,1.88,2.12
3,SC0,03/08/2025,15:00,Dundee,Hibernian,1,2,A,1,2,...,1.98,1.88,2.04,1.87,1.98,1.89,1.89,1.84,2.08,1.92
4,SC0,03/08/2025,16:30,Celtic,St Mirren,1,0,H,0,0,...,2.00,1.85,2.16,1.75,2.05,1.85,1.99,1.76,2.05,1.88
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
223,SC0,16/05/2026,12:30,Falkirk,Rangers,2,5,A,2,3,...,2.03,1.83,NaN,NaN,2.03,1.83,1.96,1.77,2.09,1.88
224,SC0,16/05/2026,12:30,Hibernian,Motherwell,0,1,A,0,1,...,1.85,2.00,NaN,NaN,1.85,2.00,1.79,1.94,1.93,2.06
225,SC0,17/05/2026,14:00,Dundee,Aberdeen,3,2,H,1,2,...,1.93,1.93,NaN,NaN,1.93,2.00,1.83,1.89,1.93,2.05
226,SC0,17/05/2026,14:00,Livingston,Kilmarnock,1,4,A,1,2,...,1.93,1.93,NaN,NaN,1.95,1.93,1.88,1.84,1.99,1.97
227,SC0,17/05/2026,14:00,St Mirren,Dundee United,1,1,D,0,1,...,2.00,1.85,NaN,NaN,2.00,1.85,1.92,1.79,2.05,1.93

In [6]:
#rename columns
df_premier26.rename(columns={'FTHG':'home_goals',
                             'FTAG':'away_goals'}, inplace=True)

In [7]:
#printing dataframe
df_premier26

,Div,Date,Time,HomeTeam,AwayTeam,home_goals,away_goals,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,SC0,02/08/2025,15:00,Kilmarnock,Livingston,2,2,D,2,0,...,2.05,1.80,1.94,1.96,2.05,1.93,1.87,1.83,2.06,1.91
1,SC0,02/08/2025,17:30,Motherwell,Rangers,1,1,D,0,1,...,2.03,1.83,2.03,1.88,2.03,1.85,1.97,1.77,2.08,1.91
2,SC0,03/08/2025,14:00,Falkirk,Dundee United,2,2,D,0,1,...,1.73,2.08,1.87,2.04,1.86,2.08,1.79,1.94,1.88,2.12
3,SC0,03/08/2025,15:00,Dundee,Hibernian,1,2,A,1,2,...,1.98,1.88,2.04,1.87,1.98,1.89,1.89,1.84,2.08,1.92
4,SC0,03/08/2025,16:30,Celtic,St Mirren,1,0,H,0,0,...,2.00,1.85,2.16,1.75,2.05,1.85,1.99,1.76,2.05,1.88
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
223,SC0,16/05/2026,12:30,Falkirk,Rangers,2,5,A,2,3,...,2.03,1.83,NaN,NaN,2.03,1.83,1.96,1.77,2.09,1.88
224,SC0,16/05/2026,12:30,Hibernian,Motherwell,0,1,A,0,1,...,1.85,2.00,NaN,NaN,1.85,2.00,1.79,1.94,1.93,2.06
225,SC0,17/05/2026,14:00,Dundee,Aberdeen,3,2,H,1,2,...,1.93,1.93,NaN,NaN,1.93,2.00,1.83,1.89,1.93,2.05
226,SC0,17/05/2026,14:00,Livingston,Kilmarnock,1,4,A,1,2,...,1.93,1.93,NaN,NaN,1.95,1.93,1.88,1.84,1.99,1.97
227,SC0,17/05/2026,14:00,St Mirren,Dundee United,1,1,D,0,1,...,2.00,1.85,NaN,NaN,2.00,1.85,1.92,1.79,2.05,1.93